import type { NextPage } from 'next';
import Head from 'next/head';
import { StartPoint } from '../components/StartPoint.component';
import styles from '../styles/Home.module.css';
const Home: NextPage = () => {
  const text = {
    name: 'Meero',
    action: 'satrt',
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StartPoint text={text} />
    </div>
  );
};

export default Home;
